
-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 18:04:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

 --Ronald david gil hurtado
 --version mySQL: 8.4.0
