-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 18:04:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`PACIENTE` (
  `PACI_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PACI_NOMBRE` VARCHAR(45) NOT NULL,
  `PACI_APELLIDO` VARCHAR(45) NOT NULL,
  `PACI_NIT` VARCHAR(45) NOT NULL,
  `PACI_EMAIL` VARCHAR(45) NOT NULL,
  `PACI_CELULAR` VARCHAR(45) NOT NULL,
  `FECHACREACION` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion del registro',
  `FECHAMODIFICACION` TIMESTAMP NULL DEFAULT NULL COMMENT 'Fecha de modificacion del registro',
  PRIMARY KEY (`PACI_ID`),
  UNIQUE INDEX `PACI_NIT_UNIQUE` (`PACI_NIT` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`HISTORIACLINICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`HISTORIACLINICA` (
  `HICL_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FECHACREACION` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de modificacion del registro',
  `FECHAMODIFICACION` TIMESTAMP NULL DEFAULT NULL COMMENT 'Fecha de modificacion del registro',
  `HICL_OBSERVACION` VARCHAR(255) NULL DEFAULT NULL,
  `HICL_MEDICAMENTO` VARCHAR(45) NOT NULL,
  `PACI_ID` BIGINT NOT NULL,
  `FECHAULTIMAVISITA` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`HICL_ID`),
  INDEX `FK_PACE_ID_idx` (`PACI_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PACE_ID`
    FOREIGN KEY (`PACI_ID`)
    REFERENCES `railway`.`PACIENTE` (`PACI_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`MEDICO` (
  `MEDI_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `MEDI_NOMBRE` VARCHAR(45) NOT NULL,
  `MEDI_APELLIDO` VARCHAR(45) NOT NULL,
  `MEDI_NIT` VARCHAR(45) NOT NULL,
  `MEDI_EMAIL` VARCHAR(45) NOT NULL,
  `FECHACREACION` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion  del registro',
  `FECHAMODIFICACION` TIMESTAMP NULL DEFAULT NULL COMMENT 'Fecha de modificacion del registro',
  `MEDI_AREA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MEDI_ID`),
  UNIQUE INDEX `MEDI_NIT_UNIQUE` (`MEDI_NIT` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`VISITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`VISITA` (
  `VIST_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `VIST_FECHAVISITA` TIMESTAMP NULL DEFAULT NULL,
  `VIST_DIAGNOSTICO` VARCHAR(255) NULL DEFAULT NULL,
  `VIST_TRATAMIENTO` VARCHAR(255) NULL DEFAULT NULL,
  `PACI_ID` BIGINT NOT NULL,
  `MEDI_ID` BIGINT NOT NULL,
  `FECHACREACION` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `FECHAMODIFICACION` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`VIST_ID`),
  INDEX `FK_PACI_ID_idx` (`PACI_ID` ASC) INVISIBLE,
  INDEX `FK_MEDIC_ID_idx` (`MEDI_ID` ASC) VISIBLE,
  CONSTRAINT `FK_MEDIC_ID`
    FOREIGN KEY (`MEDI_ID`)
    REFERENCES `railway`.`MEDICO` (`MEDI_ID`),
  CONSTRAINT `FK_PACI_ID`
    FOREIGN KEY (`PACI_ID`)
    REFERENCES `railway`.`PACIENTE` (`PACI_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `railway` ;

-- -----------------------------------------------------
-- procedure insertar_visita
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `insertar_visita`(

in LV_PacienteID  BIGINT,
in LV_MedicoID    BIGINT,
IN LV_FechaVisita  TIMESTAMP,
IN LV_Diagnostico   VARCHAR(255),
IN LV_Tratamiento  VARCHAR(255)



)
begin 

INSERT INTO `railway`.`VISITA`  (`VIST_FECHAVISITA`, `VIST_DIAGNOSTICO`, `VIST_TRATAMIENTO`, `PACI_ID`, `MEDI_ID`)  VALUES  (LV_FechaVisita, LV_Diagnostico, LV_Tratamiento , LV_PacienteID,  LV_MedicoID);

END$$

DELIMITER ;
USE `railway`;


-- -----------------------------------------------------
-- trigger visita_after_insert
-- -----------------------------------------------------
DELIMITER $$
USE `railway`$$
CREATE
DEFINER=`root`@`%`
TRIGGER `railway`.`VISITA_AFTER_INSERT`
AFTER INSERT ON `railway`.`VISITA`
FOR EACH ROW
BEGIN
 UPDATE  RAILWAY.HISTORIACLINICA
 SET FECHAULTIMAVISITA =  sysdate()
  where  PACI_ID = new.PACI_ID;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
